version: "3.9"

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
        - static_volume:/app/backend/django_static
    entrypoint: /app/scripts/django.sh
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    container_name: celery
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/scripts/worker-entrypoint.sh
    env_file:
      - .env
    volumes:
      - static_volume:/app/food_order/django_static
    depends_on:
      - djangoapp

  redis:
      restart: unless-stopped
      image: redis:7.0.5-alpine 
      expose:
          - 6379
  db:
    container_name: db
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/

volumes:
    static_volume:
    postgres_data:
