# Generated by Django 4.2 on 2023-11-15 18:52

from django.db import migrations
from rest_framework_simplejwt.tokens import RefreshToken


def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    USERNAME = "allenjose"
    PASSWORD = "password"
    EMAIL = "allenjose07@gmail.com"

    user = get_user_model()

    if not user.objects.filter(username=USERNAME, email=EMAIL).exists():
        print("Creating new superuser")
        admin = user.objects.create_superuser(
            username=USERNAME,
            password=PASSWORD,
            email=EMAIL,
            phone="+17907512638",
            user_type="admin",
        )
        admin.save()
        refresh = RefreshToken.for_user(admin)
        print("==================", str(refresh.access_token), "==================")
    else:
        print("Superuser already created!")


class Migration(migrations.Migration):
    dependencies = [
        (
            "food_order_api",
            "0002_user_groups_user_user_permissions_alter_order_id_and_more",
        ),
    ]
    operations = [migrations.RunPython(generate_superuser)]
