# Generated by Django 4.2 on 2023-11-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_order_api", "0003_superusercreation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="food_type",
        ),
        migrations.RemoveField(
            model_name="userorder",
            name="items",
        ),
        migrations.RemoveField(
            model_name="userorder",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("delivered", "Delivery"),
                    ("canceled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="otp",
            field=models.CharField(default=123456, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="payment_option",
            field=models.CharField(default="COD", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=60,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="product_items",
                through="food_order_api.OrderItem",
                to="food_order_api.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=60,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=60,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="FoodItem",
        ),
        migrations.DeleteModel(
            name="FoodType",
        ),
        migrations.DeleteModel(
            name="UserOrder",
        ),
    ]
