# Generated by Django 4.2 on 2023-11-17 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "food_order_api",
            "0004_remove_fooditem_food_type_remove_userorder_items_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
