# Generated by Django 4.2 on 2023-11-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_order_api", "0005_order_delivery_agent_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
